"""empty message

Revision ID: cb8e194b8f8f
Revises: 
Create Date: 2024-11-27 23:25:07.705235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb8e194b8f8f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professional_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_type', sa.Integer(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'service', ['service_type'], ['type_of_service'])
        batch_op.drop_column('id')
        batch_op.drop_column('service_id')

    with op.batch_alter_table('service_request', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'professional_details', ['professional_id'], ['user_id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('service_request', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'professional_details', ['professional_id'], ['id'])

    with op.batch_alter_table('professional_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'service', ['service_id'], ['id'])
        batch_op.drop_column('service_type')

    # ### end Alembic commands ###
